version: 1

# Hexagonal Architecture - Dependency Flow: domain <- ports <- app <- adapters

components:
  - name: diff-domain
    in: internal/diff/domain

  - name: diff-ports
    in: internal/diff/ports
    mayDependOn: [diff-domain]

  - name: diff-app
    in: internal/diff/app
    mayDependOn: [diff-domain, diff-ports]

  - name: diff-adapters
    in: internal/diff/adapters
    mayDependOn: [diff-domain, diff-ports, platform]

  - name: platform
    in: internal/platform

rules:
  - from: diff-domain
    shouldNot: [{dependOn: [diff-ports, diff-app, diff-adapters, platform]}]

  - from: diff-ports
    shouldNot: [{dependOn: [diff-app, diff-adapters, platform]}]

  - from: diff-app
    shouldNot: [{dependOn: [diff-adapters, platform]}]

  - from: diff-adapters
    shouldNot: [{dependOn: [diff-app, diff-adapters]}]

exclude:
  - testdata
  - vendor
  - "**/*_test.go"
